CREATE TABLE IF NOT EXISTS `NEWS`(
   `ID` INT UNSIGNED,
   `GP` VARCHAR(50),
   `SITE` VARCHAR(50),
   `TITLE` VARCHAR(200),
   `URL` VARCHAR(250),
   `TIME` VARCHAR(50),
   `SN` INT AUTO_INCREMENT Unique,
   PRIMARY KEY ( `ID` )
)ENGINE=InnoDB DEFAULT CHARSET=utf8;